### ISSUE TITLE
 no known conversion for argument 2 from ‘cv::Mat’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&’

### ISSUE THREAD

**Issue by rhan-Lau** [koide3/ccf_person_identification#1]
Hi, I'm trying to catkin_make this ccf_person_identification module and use it in the monocular_person_following project, and then I got this error saying that no known conversion for argument 2 from ‘cv::Mat’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&’ , the whole error message is shown as below:

/home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp: In function ‘int main(int, char**)’:
/home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:51:44: error: no matching function for call to ‘ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, cv::Mat&)’
         classifier->extractInput(input, pos);
                                            ^
In file included from /home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:6:0:
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note: candidate: virtual bool ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&)
     virtual bool extractInput(Input::Ptr& input, const std::unordered_map<std::string, cv::Mat>& images) override {
                  ^~~~~~~~~~~~
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note:   no known conversion for argument 2 from ‘cv::Mat’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&’
/home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:58:45: error: no matching function for call to ‘ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, cv::Mat&)’
         classifier->extractInput(input, neg1);
                                             ^
In file included from /home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:6:0:
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note: candidate: virtual bool ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&)
     virtual bool extractInput(Input::Ptr& input, const std::unordered_map<std::string, cv::Mat>& images) override {
                  ^~~~~~~~~~~~
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note:   no known conversion for argument 2 from ‘cv::Mat’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&’
/home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:65:45: error: no matching function for call to ‘ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, cv::Mat&)’
         classifier->extractInput(input, neg2);
                                             ^
In file included from /home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:6:0:
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note: candidate: virtual bool ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&)
     virtual bool extractInput(Input::Ptr& input, const std::unordered_map<std::string, cv::Mat>& images) override {
                  ^~~~~~~~~~~~
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note:   no known conversion for argument 2 from ‘cv::Mat’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&’
/home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:89:48: error: no matching function for call to ‘ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, cv::Mat&)’
             classifier->extractInput(input, pos);
                                                ^
In file included from /home/han/catkin_ws/src/ccf_person_identification/src/ccf_person_identification_test.cpp:6:0:
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note: candidate: virtual bool ccf_person_classifier::PersonClassifier::extractInput(ccf_person_classifier::Input::Ptr&, const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&)
     virtual bool extractInput(Input::Ptr& input, const std::unordered_map<std::string, cv::Mat>& images) override {
                  ^~~~~~~~~~~~
/home/han/catkin_ws/src/ccf_person_identification/include/ccf_person_identification/person_classifier.hpp:63:18: note:   no known conversion for argument 2 from ‘cv::Mat’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, cv::Mat>&’

I kind of stuck here now, can anyone please help me find out why this happened? Any advice would be appreciated.

**Comment by koide3** [comment]
Hi @rhan-Lau ,
It seems the error is caused by some updates in the person classifier which I made for face recognition. I pushed updated ccf_person_identification_test.cpp. Can you check if it works?

**Comment by rhan-Lau** [comment]
Yes, the new code worked very well, thank you very much @koide3.
However, I got one more question: When I test the whole monocular_person_following project before, I cannot get the feature image and MarkerArray in the rviz,  when I use "rostopic echo /monocular_person_following/feature" to show the topic, it says that the topic does not appear to be published yet. I used to think it is something wrong with the ccf module, but it doesn't changed with the new code. 
Do you have any idea about this?
![Screenshot from 2019-10-29 19-48-49](https://user-images.githubusercontent.com/27419908/67839038-9e554800-fb2d-11e9-9e1e-77559b28ca3b.png)

**Comment by koide3** [comment]
It is not relevant to the original topic of this issue. Please re-open a new issue in monocular_person_following repository.

**Comment by rhan-Lau** [comment]
OK, I will. Since the problem is fixed, I will close this issue and re-open another one for the new issue. Thank you again for ur help on this issue.
